name: Generate SARIF with Semgrep and upload it to Github
description: |
  Utilizes Semgrep to generate a SARIF report. The report is archived and uploaded to Github.

  Uses https://github.com/kronostechnologies/standards/blob/master/bin/semgrep.sh to normalize results.

inputs:
  language:
    description: The language check to run. Can be one of [ kt, ts, py ].
    required: true
  report-name:
    description: Override the default report name. This is useful for workflows that output multiple Semgrep reports.
    required: false
    default: "semgrep"
  report-retention-days:
    description: Duration in days to preserve reports.
    required: true
    default: "5"
  working-directory:
    description: Relative path under $GITHUB_WORKSPACE where the root project is located.
    required: false
    default: "."

runs:
  using: composite
  steps:
    - name: Action context
      id: context
      shell: bash
      run: |
        working_directory=$(realpath ${{ inputs.working-directory }})
        echo "::set-output name=working-directory::$working_directory"
        echo "::set-output name=sarif-file::build/sast/${{ inputs.report-name }}.sarif"

    - name: Semgrep
      working-directory: ${{ steps.context.outputs.working-directory }}
      shell: bash
      run: |
        ${{ github.action_path }}/files/semgrep.bash \
          -l "${{ inputs.language }}" \
          -o "${{ steps.context.outputs.sarif-file }}"

        result=$?
        if [ $result -ne 0 ]; then
          exit $result
        fi

    - uses: actions/upload-artifact@v3
      if: "!cancelled()"
      with:
        name: ${{ inputs.report-name }}.sarif
        path: ${{ steps.context.outputs.working-directory }}/${{ steps.context.outputs.sarif-file }}
        retention-days: ${{ inputs.report-retention-days }}

    - name: Publish report
      uses: github/codeql-action/upload-sarif@v2
      with:
        category: ${{ inputs.report-name }}
        sarif_file: ${{ inputs.working-directory }}/${{ steps.context.outputs.sarif-file }}
